class WeaponStats {
  final String name;
  final double damage;
  final double fireRate; // seconds between shots
  final int magSize;
  final int reserveAmmo;
  final double reloadTime;
  final double spread; // radians
  final double bulletSpeed;
  final int bulletCount;
  final double range;
  final String type;
  final int color; // hex color
  final bool splash;
  final double splashRadius;
  final WeaponStats? pap;

  const WeaponStats({
    required this.name,
    required this.damage,
    required this.fireRate,
    required this.magSize,
    required this.reserveAmmo,
    required this.reloadTime,
    required this.spread,
    required this.bulletSpeed,
    required this.bulletCount,
    required this.range,
    required this.type,
    required this.color,
    this.splash = false,
    this.splashRadius = 0,
    this.pap,
  });
}

class WeaponData {
  static const Map<String, WeaponStats> weapons = {
    'm1911': WeaponStats(
      name: 'M1911',
      damage: 30,
      fireRate: 0.2,
      magSize: 8,
      reserveAmmo: 80,
      reloadTime: 1.5,
      spread: 0.05,
      bulletSpeed: 15,
      bulletCount: 1,
      range: 500,
      type: 'pistol',
      color: 0xFFFFD700,
      pap: WeaponStats(
        name: 'Mustang',
        damage: 80,
        fireRate: 0.15,
        magSize: 12,
        reserveAmmo: 120,
        reloadTime: 1.2,
        spread: 0.04,
        bulletSpeed: 18,
        bulletCount: 1,
        range: 550,
        type: 'pistol',
        color: 0xFFFF4500,
      ),
    ),
    'mp40': WeaponStats(
      name: 'MP40',
      damage: 40,
      fireRate: 0.08,
      magSize: 32,
      reserveAmmo: 192,
      reloadTime: 2.0,
      spread: 0.08,
      bulletSpeed: 14,
      bulletCount: 1,
      range: 400,
      type: 'smg',
      color: 0xFF87CEEB,
      pap: WeaponStats(
        name: 'The Afterburner',
        damage: 100,
        fireRate: 0.06,
        magSize: 64,
        reserveAmmo: 256,
        reloadTime: 1.8,
        spread: 0.06,
        bulletSpeed: 16,
        bulletCount: 1,
        range: 450,
        type: 'smg',
        color: 0xFF00BFFF,
      ),
    ),
    'olympia': WeaponStats(
      name: 'Olympia',
      damage: 80,
      fireRate: 0.6,
      magSize: 2,
      reserveAmmo: 38,
      reloadTime: 2.5,
      spread: 0.25,
      bulletSpeed: 12,
      bulletCount: 8,
      range: 250,
      type: 'shotgun',
      color: 0xFFFF6347,
      pap: WeaponStats(
        name: 'Hades',
        damage: 200,
        fireRate: 0.5,
        magSize: 2,
        reserveAmmo: 60,
        reloadTime: 2.0,
        spread: 0.2,
        bulletSpeed: 14,
        bulletCount: 12,
        range: 300,
        type: 'shotgun',
        color: 0xFFFF0000,
      ),
    ),
    'ak47': WeaponStats(
      name: 'AK-47',
      damage: 55,
      fireRate: 0.1,
      magSize: 30,
      reserveAmmo: 270,
      reloadTime: 2.2,
      spread: 0.06,
      bulletSpeed: 16,
      bulletCount: 1,
      range: 550,
      type: 'assault',
      color: 0xFFFFA500,
      pap: WeaponStats(
        name: "Reznov's Revenge",
        damage: 140,
        fireRate: 0.08,
        magSize: 40,
        reserveAmmo: 360,
        reloadTime: 1.8,
        spread: 0.04,
        bulletSpeed: 20,
        bulletCount: 1,
        range: 650,
        type: 'assault',
        color: 0xFFFF4500,
      ),
    ),
    'm16': WeaponStats(
      name: 'M16',
      damage: 60,
      fireRate: 0.12,
      magSize: 30,
      reserveAmmo: 240,
      reloadTime: 2.0,
      spread: 0.04,
      bulletSpeed: 18,
      bulletCount: 1,
      range: 600,
      type: 'assault',
      color: 0xFF00FF7F,
      pap: WeaponStats(
        name: 'Skullcrusher',
        damage: 150,
        fireRate: 0.09,
        magSize: 45,
        reserveAmmo: 360,
        reloadTime: 1.6,
        spread: 0.03,
        bulletSpeed: 22,
        bulletCount: 1,
        range: 700,
        type: 'assault',
        color: 0xFF00FF00,
      ),
    ),
    'rpk': WeaponStats(
      name: 'RPK',
      damage: 50,
      fireRate: 0.09,
      magSize: 75,
      reserveAmmo: 375,
      reloadTime: 3.5,
      spread: 0.07,
      bulletSpeed: 15,
      bulletCount: 1,
      range: 500,
      type: 'lmg',
      color: 0xFFDAA520,
      pap: WeaponStats(
        name: 'R115 Resonator',
        damage: 130,
        fireRate: 0.07,
        magSize: 125,
        reserveAmmo: 500,
        reloadTime: 3.0,
        spread: 0.05,
        bulletSpeed: 18,
        bulletCount: 1,
        range: 600,
        type: 'lmg',
        color: 0xFFFFD700,
      ),
    ),
    'dragunov': WeaponStats(
      name: 'Dragunov',
      damage: 200,
      fireRate: 0.5,
      magSize: 10,
      reserveAmmo: 40,
      reloadTime: 2.8,
      spread: 0.01,
      bulletSpeed: 25,
      bulletCount: 1,
      range: 900,
      type: 'sniper',
      color: 0xFF9370DB,
      pap: WeaponStats(
        name: 'D115 Disassembler',
        damage: 500,
        fireRate: 0.4,
        magSize: 10,
        reserveAmmo: 80,
        reloadTime: 2.2,
        spread: 0.008,
        bulletSpeed: 30,
        bulletCount: 1,
        range: 1100,
        type: 'sniper',
        color: 0xFF8A2BE2,
      ),
    ),
    'raygun': WeaponStats(
      name: 'Ray Gun',
      damage: 150,
      fireRate: 0.3,
      magSize: 20,
      reserveAmmo: 160,
      reloadTime: 2.0,
      spread: 0.02,
      bulletSpeed: 12,
      bulletCount: 1,
      range: 700,
      type: 'wonder',
      color: 0xFF00FF00,
      splash: true,
      splashRadius: 60,
      pap: WeaponStats(
        name: "Porter's X2 Ray Gun",
        damage: 400,
        fireRate: 0.25,
        magSize: 40,
        reserveAmmo: 200,
        reloadTime: 1.5,
        spread: 0.015,
        bulletSpeed: 14,
        bulletCount: 1,
        range: 800,
        type: 'wonder',
        color: 0xFF39FF14,
        splash: true,
        splashRadius: 80,
      ),
    ),
  };

  static const List<String> mysteryBoxPool = [
    'mp40', 'olympia', 'ak47', 'm16', 'rpk', 'dragunov', 'raygun',
  ];

  static const Map<String, int> wallWeaponCosts = {
    'olympia': 500,
    'mp40': 1000,
  };
}
